### ISSUE TITLE
Errors during training

### ISSUE THREAD

**Issue by SM-93** [Beckschen/TransUNet#15]
Hi! 
I got this errors while running training:
```
File "train.py", line 93, in <module>
    trainer[dataset_name](args, net, snapshot_path)
  File "/home/ubuntu/projects/TransUNet/trainer.py", line 57, in trainer_synapse
    loss_dice = dice_loss(outputs, label_batch, softmax=True)
  File "/home/ubuntu/miniconda3/envs/transunet/lib/python3.7/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/ubuntu/projects/TransUNet/utils.py", line 43, in forward
    class_wise_dice.append(1.0 - dice.item())
RuntimeError: CUDA error: device-side assert triggered
```

I inspect the shapes:
**label_batch**  (24, 224, 224);
**outputs** (24, 9, 224, 224);
**image_batch** (24, 1, 224, 224)

Then when I try to debug it, points me to another error:
```
CUDA error: device-side assert triggered
  File "/home/ubuntu/projects/TransUNet/utils.py", line 34, in forward
    inputs = torch.softmax(inputs, dim=1)
  File "/home/ubuntu/miniconda3/envs/transunet/lib/python3.7/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/ubuntu/projects/TransUNet/trainer.py", line 57, in trainer_synapse
    loss_dice = dice_loss(outputs, label_batch, softmax=True)
  File "/home/ubuntu/projects/TransUNet/train.py", line 93, in <module>
    trainer[dataset_name](args, net, snapshot_path)
  File "/home/ubuntu/miniconda3/envs/transunet/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/ubuntu/miniconda3/envs/transunet/lib/python3.7/runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "/home/ubuntu/miniconda3/envs/transunet/lib/python3.7/runpy.py", line 263, in run_path
    pkg_name=pkg_name, script_name=fname)
  File "/home/ubuntu/miniconda3/envs/transunet/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/ubuntu/miniconda3/envs/transunet/lib/python3.7/runpy.py", line 193, in _run_module_as_main (Current frame)
    "__main__", mod_spec)
```

Again inspect the shapes:
**inputs** (24, 9, 224, 224)
**target** (24, 224, 224)

I would appreciate it if you can help me with this :)

P.S. I preprocessed the images as it was described (i.e. clipped, normalized and extracted the slices)

**Comment by SM-93** [comment]
Hi, just wanted to let you know that I figured out the problem. 
Since the maximum value of the class was 13 in my label images, I set num_classes to 14 actually and then it runs the script without errors.
I saw in your paper that you trained on 8 abdominal organs, I guess that is why you set the num_classes to 9.

**Comment by JAYCHOU2020** [comment]
> Hi, just wanted to let you know that I figured out the problem. Since the maximum value of the class was 13 in my label images, I set num_classes to 14 actually and then it runs the script without errors. I saw in your paper that you trained on 8 abdominal organs, I guess that is why you set the num_classes to 9.

Can I ask you how to train my dataset with 8 classes? When generating the pnz file, do I need to put the labels of the same category in a single pnz file?
